name: 'Package plugin'
description: 'Packages the plugin for specified architecture and build config.'
inputs:
  path:
    description: 'Single or multiple files to codesign.'
    required: true
  keychainProfile:
    description: 'Keychain profile for xcrun.'
    required: true
  workingDirectory:
    description: 'Working directory.'
    required: false
    defaults: .
  verbose:
    description: 'Enable printing command lines.'
    required: false
    defaults: false
    type: boolean
  saveLog:
    description: 'Save log files.'
    required: false
    defaults: true
    type: boolean
runs:
  using: 'composite'
  steps:
    - name: Notarize
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        if test "${{ inputs.verbose }}" != false; then
          set -x
        fi
        cd "${{ inputs.workingDirectory }}"
        for pkg in ${{ inputs.path }}; do
          echo "Notarizing $pkg"
          xcrun notarytool submit "$pkg" --keychain-profile AC_PASSWORD --wait | tee submit.out
          id=$(awk '$1=="id:"{id=$2} END{print id}' submit.out)
          if ! grep -q 'status: Accepted' submit.out; then
            xcrun notarytool log "$id" --keychain-profile AC_PASSWORD ${pkg}.notarylog.json
            cat ${pkg}.notarylog.json
          elif test "${{ inputs.saveLog }}" != false; then
            xcrun notarytool log "$id" --keychain-profile AC_PASSWORD ${pkg}.notarylog.json
          fi
        done
    - name: Staple
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        if test "${{ inputs.verbose }}" != false; then
          export VERBOSE=1
          set -x
        fi
        cd "${{ inputs.workingDirectory }}"
        for pkg in ${{ inputs.path }}; do
          case "$pkg" in
            *.zip)
              ;;
            *.notarylog.json)
              ;;
            *)
              xcrun stapler staple "$pkg"
              ;;
          esac
        done
